#!/bin/sh
# prerm script for apt-mgr

set -e

case "$1" in
    remove|upgrade)
        # Clean up completion files
        rm -f /usr/share/bash-completion/completions/apt-mgr
        rm -f /usr/share/zsh/vendor-completions/_apt-mgr
        ;;
    
    failed-upgrade)
        ;;
    
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
