#!/bin/sh
# prerm script for pkgmgr

set -e

case "$1" in
    remove|upgrade)
        # Clean up completion files
        rm -f /usr/share/bash-completion/completions/pkgmgr
        rm -f /usr/share/zsh/vendor-completions/_pkgmgr
        ;;
    
    failed-upgrade)
        ;;
    
    *)
        echo "prerm called with unknown argument " >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
